language: java
branches:
  only:
  - develop

services:
  - docker

before_script:
  - docker-compose up -d --force-recreate
  - docker-compose ps

script:
  - mvn test

cache:
  directories:
    - .autoconf
    - $HOME/.m2