language: java
branches:
  only:
  - develop

services:
  - docker

before_script:
  - docker-compose up -d --force-recreate maria_db
  - docker-compose up -d --force-recreate 310-project mvn test
  - docker-compose ps

script:
  # - mvn test

cache:
  directories:
    - .autoconf
    - $HOME/.m2